version: '3.1'
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: booiscutie
      POSTGRES_USER: postgres
      POSTGRES_DB: helpdesk
    ports:
      - "5432:5432"
    networks:
      - postgres-network
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - postgres-network
networks:
  postgres-network:
    driver: bridge
    