version: '3.1'
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: "booiscutie"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "helpdesk"
    ports:
      - "5432:5432"
    volumes:
      - ./prisma-data:/var/lib/postgresql/data
volumes:
  prisma-data: